### ISSUE TITLE
1.7 compatibility

### ISSUE THREAD

**Issue by thongly** [stephenmcd/django-forms-builder#133]
I was wondering if anyone is working on 1.7 compatibility already, and if so, whether I can contribute as well. Just let me know which branch. Thanks!

**Comment by jaap3** [comment]
Created migrations in PR #152

**Comment by stephenmcd** [comment]
Just released 0.12 with 1.7 support thanks to @jaap3

**Comment by mkesper** [comment]
0.12.1 still depends on the now optional 'Site' feature:
ERRORS: forms.Form.sites: (fields.E300) Field defines a relation with model 'Site', which is either not installed, or is abstract.

**Comment by amfarrell** [comment]
If you come upon this error and want to just work around it, add 'django.contrib.sites' to your INSTALLED_APPS.
