### ISSUE TITLE
Clean installation error: no SITE_ID

### ISSUE THREAD

**Issue by alexef** [stephenmcd/django-forms-builder#142]
I'm getting: `AttributeError: 'Settings' object has no attribute 'SITE_ID'`. I guess I can set it in settings.py, but the README must be updated accordingly.

**Comment by shayneoneill** [comment]
This actually needs to be in documentation. Its an optional feature now (Since nobody really used it, and its more trouble than its worth generally).

**Comment by stephenmcd** [comment]
I've just pushed 0.12.1 with a fix for this:

3db728e9a45a890d772c356e0921c47ce403ac43

Thanks @shayneoneill and @alexef

**Comment by shayneoneill** [comment]
Thanks man!
