### ISSUE TITLE
Using templatetag with slug

### ISSUE THREAD

**Issue by kurdiplyas** [stephenmcd/django-forms-builder#151]
Hi, Stephen. 
First of all Thank you very, very much for this apps.
May be you could help me, because I'm quit new in Django. So my Issue is:
Django-forms-builder installed correctly and work properly. 
1) I create a form in admin interface with slug - "part"
2) I have template below:

{% extends 'base.html' %}
{% load bootstrap_toolkit %}
{% load forms_builder_tags %}
 
{% block content %}
 
<div class="info-block international">
    <div class="title">Форма регистрации</div>
    <div class="content about">
          {% render_built_form slug=form.part %}
    </div>
</div>
{% endblock %}

But when i try to reach the page I catch : 

VariableDoesNotExist at /reg
Failed lookup for key [part] in u"<module 'forms_builder.forms' from '/home/sergey/venv/local/lib/python2.7/site-packages/forms_builder/forms/__init__.pyc'>"

Full trace here http://pastebin.com/472kJ4VW

**Comment by stephenmcd** [comment]
Could you post this to the django-users mailing list instead? It's really not a forms builder issue.

Thanks
