### ISSUE TITLE
Feature request: A way to add paragraphs between fields.

### ISSUE THREAD

**Issue by jonearley** [stephenmcd/django-forms-builder#158]
I don't see a clear way to add content between fields. Could this be implemented?

**Comment by barseghyanartur** [comment]
@jonearley 

See this:

- https://gist.github.com/barseghyanartur/c6e0123dd961fbac1b39

Or switch to another form builder:

- https://www.djangopackages.com/grids/g/form-builder/

**Comment by stephenmcd** [comment]
Thanks @barseghyanartur - that's a neat recipe!
