### ISSUE TITLE
Feature request: ability to select which fields end up in mail to form submitter

### ISSUE THREAD

**Issue by GregorKopka** [stephenmcd/django-forms-builder#162]
Title tells it all: Ability to select if the field will end up in the mail to the one who completed the form

**Comment by stephenmcd** [comment]
Not interested in this sorry.

**Comment by stephenmcd** [comment]
BTW if necessary, you can simply customize the email template to check for particular fields and either show them or not.

**Comment by GregorKopka** [comment]
You can't specify a template on a per-form basis (at least not visible from the admin) so this would work global. In the end it would confuse end-users since for them fields would simply not show up in the mail without any visible reason why.
