### ISSUE TITLE
Feature request: Ability to select if mail is to be sent to form submitter

### ISSUE THREAD

**Issue by GregorKopka** [stephenmcd/django-forms-builder#163]
There are use cases in which a mail to the one who submits the form might not be desired, a checkbox to enable mail only to the ones in 'sent copies to' would be helpful.

**Comment by stephenmcd** [comment]
This exists already.

**Comment by GregorKopka** [comment]
I have found it after playing with the options.

The admin screen (german version) was misguiding, since it suggests (at least to me) that disabling the checkbox under 'E-Mail versenden' (i guess 'Send email') will also disable 'Sende Kopien an' ('Send copies to') - reasoning is that if there is no initial mail there can't be any copies.

Maybe a different description for the options might keep others that don't already know what i know now from making the mistake i made.
