### ISSUE TITLE
Calling forms programmatically 

### ISSUE THREAD

**Issue by Sergiodiaz53** [stephenmcd/django-forms-builder#166]
Hi, 

I have installed the django-forms-builder in my aplication. This way unexperienced admins could create forms that I use to call services.

The problem is that, until now, I created the forms programmatically and generate the interface this way:
```python
    def serviceInterface(request):
    if request.method == 'POST':
            service = Script.objects.get(exeName=request.POST.get('exeName'))
            files = listUserFiles(request)
            myForm= getattr(forms, service.form)
            form = myForm(user = request.user, request = request)
            return render(request, 'serviceInterface.html', {'name': service.name, 'exeName': service.exeName, 'files': files, 'form': form})
 ```

and in my forms.py: 

```python
class serviceForm(forms.Form):
    filename = forms.ChoiceField(label="Filename", widget=forms.Select(attrs={'class':'selector'}))
    K = forms.CharField(label='K', max_length=1)
    fullOut = forms.CharField(label='fullOut', max_length=1)
````

The problem here is that I can't get forms generated by the django-form-builder. How could I get them? I can port all my forms to django-form-builder and modify my serviceInterface view

**Comment by stephenmcd** [comment]
Can't help you there, you might like to try stackoverflow or the django-users mailing list.
