### ISSUE TITLE
Get POST fields

### ISSUE THREAD

**Issue by Sergiodiaz53** [stephenmcd/django-forms-builder#169]
Hi,

I'm trying to get the parameters sended in the POST from my own. I have seen that Submit petitions are sended to /forms/formname/ and that you could put a 'redirect URL'. Is there anyway to received the data in that URL? because what I have done is to redirect to an URL which have a view like this:

     def testForm(request):
         print request
         return HttpResponse("OK", content_type="text/plain")

But the request doesn't have that info.
Thanks in advance

**Comment by stephenmcd** [comment]
Can't help you there, maybe try stackoverflow.
