### ISSUE TITLE
Django 1.9 support

### ISSUE THREAD

**Issue by isoboroff** [stephenmcd/django-forms-builder#176]
I didn't see any indication of whether this package will grow beyond Django 1.7.  Are there plans to bring it up to date with current Django?

**Comment by stephenmcd** [comment]
Would you like to work on it?

**Comment by isoboroff** [comment]
Any idea what's involved?  How do I start to figure out if I can do this?

**Comment by isoboroff** [comment]
Started skimming 1.8/1.9 release notes and code here. I have a Django project I'm working on and would like to use DFB, so time permitting I'll see what I can do here.

**Comment by movie4** [comment]
+1

**Comment by leonh** [comment]
I've installed it in a 1.9.2 django project and it appears to be working OK. Haven't given it a thorough  test though. 
There was one minor problem: 
The view on site link in the admin change form was causing an error ( however the view on site link in the admin change list works)

**Comment by zixan** [comment]
@leonh are there any other changes you made other than: https://github.com/leonh/django-forms-builder/commit/5a1b65a8d1a1b9995a4dece5272db23e3ebf645e

**Comment by leonh** [comment]
That commit includes my project customisation which you won't need . Just look at the admin change_form.html. 1.9 comparability was not too difficult to achieve though you may want to use better approach than mine

**Comment by kdiale-nerdery** [comment]
Are the comments on the pull request the only thing holding a merge back? Are there test failures?

**Comment by kdiale-nerdery** [comment]
Let me know what concretely needs to happen here and I'll gladly jump in and get this thing up to snuff. I'd love to see this functional on django 1.9

**Comment by stephenmcd** [comment]
Just the comments in the PR I guess

**Comment by joesanford** [comment]
It looks like the version on PyPi is not up to date with the repo, and the `from django.utils.importlib import import_module` import statement in `utils.py` is still in PyPi, which causes issues with pip installations with Django 1.9.

**Comment by stephenmcd** [comment]
0.12.3 is on PyPI now.
