### ISSUE TITLE
Don't Require settings.SITE_ID

### ISSUE THREAD

**Issue by jpotterm** [stephenmcd/django-forms-builder#181]
In `forms/settings.py` you raise an `ImproperlyConfigured` exception if `SITE_ID` is not defined, however Django allows the use of the sites framework without defining `SITE_ID`. According to the [documentation](https://docs.djangoproject.com/en/1.9/ref/contrib/sites/#get-current-site-shortcut):

> It looks up the current site based on request.get_host() if the SITE_ID setting is not defined.

I propose only requiring `SITE_ID` to be set when `FORMS_BUILDER_USE_SITES = True`

**Comment by juandgc** [comment]
I agree

**Comment by stephenmcd** [comment]
That's done - note you'll still potentially get errors with Django admin without either an explicit `SITE_ID` setting, or a matching host, since the sites app is still required to keep forms_buillder's migrations simple.
