### ISSUE TITLE
No tag in github for 0.12.2 release?

### ISSUE THREAD

**Issue by cworth-gh** [stephenmcd/django-forms-builder#183]
The latest tag I see in the git repository is for 0.7.15 (from Sep. 6, 2012), yet I see a 0.12.2 release on pypi. I've been trying to determine the code from which that release was made and the missing tag is making that difficult.

**Comment by stephenmcd** [comment]
https://github.com/stephenmcd/django-forms-builder/commits/master/forms_builder/__init__.py
