### ISSUE TITLE
PIP needs updated version for django 1.10

### ISSUE THREAD

**Issue by chozabu** [stephenmcd/django-forms-builder#194]
This commit - https://github.com/stephenmcd/django-forms-builder/commit/2b9cfd5f504e7d51da5d57c31beed9edeb5ac056
Fixes an issue stopping a django 1.10 app from launching

the latest version on pip seems to be newer than this commit, but lacking the change

**Comment by stephenmcd** [comment]
No need to open an issue for this since it's already resolved. You can certainly use pip to install directly from the latest commit on GitHub.

**Comment by chozabu** [comment]
@stephenmcd Sure - you can install directly from git, but in the readme it says

> The easiest way to install django-forms-builder is directly from PyPi using pip by running the command below:
> 
>     $ pip install -U django-forms-builder
> 

perhaps if the pip build will not be updated, this should be changed to `pip install git+https://github.com/stephenmcd/django-forms-builder.git` so people can follow the readme and have a working install?

As it stands, people I am working with changed the failing import line to `from django.conf.urls import *` - and I'm sure other people around the world will be doing similar solutions to work around not knowing why there seems to be an error in a well known library
