### ISSUE TITLE
Feature Request: Ability to specify a rendering template for individual forms

### ISSUE THREAD

**Issue by jciskey** [stephenmcd/django-forms-builder#196]
It would be extremely useful to be able to specify what template should be used to render a specific form. The default form template can be overridden, but it still gets used for all forms, which is extremely limiting when some forms need special styling compared to others. I suppose it's possible to do a comparison to the form ID in the template and use a separate setup based on that, but that particular solution seems extremely hacky and un-Django-like.

This feature would add a single option to the admin interface for editing forms that lets the user specify the template to use for that form (probably as a dropdown pulling from a project settings variable, to avoid injection risks from user data). It would then modify the `BuiltFormNode.render` method to pull the form-specific template, defaulting to the built-in template if none exists or was specified.

I would be willing to do the codework to get this functional and provide a pull request, but I don't want to do so if the feature doesn't align with project goals.

**Comment by jedie** [comment]
ping...

+1

**Comment by stephenmcd** [comment]
I think this is best implemented via templates as you described.
