### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by niamulrox** [stephenmcd/django-forms-builder#201]
Hi,

Please check the error image

https://www.dropbox.com/s/r9h1no8md0o2p27/Screenshot%202017-09-13%2017.34.22.png?dl=0

Request Method: | GET
-- | --
http://localhost:9002/en/admin/forms/form/
1.10.8
NoReverseMatch
Reverse for 'form_detail' with arguments '()' and keyword arguments '{u'slug': u'contact-us'}' not found. 0 pattern(s) tried: []
/Library/Python/2.7/site-packages/django/urls/resolvers.py in _reverse_with_prefix, line 392
/usr/bin/python
2.7.10
['/Volumes/Storage/devil/market/docroot/python/iiabd',  '/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg',  '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip',  '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7',  '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin',  '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac',  '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages',  '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk',  '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old',  '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload',  '/Library/Python/2.7/site-packages',  '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python',  '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC']
Wed, 13 Sep 2017 17:30:11 +0600

**Comment by stephenmcd** [comment]
Presumably you've not configured your urlpatterns correctly, but either way, I can't help you troubleshoot your own code sorry - you might like to try stackoverflow.
