### ISSUE TITLE
Extend dependency to Django 1.11

### ISSUE THREAD

**Issue by zbohm** [stephenmcd/django-forms-builder#207]
Hi Stephen,
it is possible to extend dependency to Django 1.11. and [django-email-extras](https://github.com/stephenmcd/django-email-extras/issues/43).

setup.py:
```python
        install_requires = [
            ....
            "django-email-extras >= 0.3.3",
            "django >= 1.8, <= 1.11",
            ....
        ],
```

**Comment by metteludwig** [comment]
Solved with pull request #209

**Comment by jedie** [comment]
Please Update PyPi Package, too!

**Comment by bashu** [comment]
@stephenmcd +1 for pypi package

**Comment by stephenmcd** [comment]
97ee3855204d9d6a33c097319e2135a817d5047f
