### ISSUE TITLE
Support, maintenance and updates

### ISSUE THREAD

**Issue by qcaron** [stephenmcd/django-forms-builder#215]
Hi @stephenmcd,

I noticed that some pull requests and issues have been standing there for a while now.

I would like to create a PR for the `views.form_set`, but I am wondering if it would be landed in a near future (if approved of course).

Could you give us a status of this project? Should new admins be integrated? Would we rather create our own fork?

Cheers,
Quentin

**Comment by barseghyanartur** [comment]
@qcaron:

I would not know it for sure, but from what I've seen so far - it's dead, man. The only projects that would likely still get maintenance are `mezzanine` and `cartridge`. The rest are left to die peacefully.

**Comment by qcaron** [comment]
Thanks for your answer @barseghyanartur.  

Would anyone be interested in this package to be forked to create a `django-forms-builder2`? 

Would anyone be also willing to give this package a few hours a month for guidance, maintenance, tests and improvements?

@stephenmcd: adding new admins would still a better solution. Please let us know 😉

**Comment by barseghyanartur** [comment]
@qcaron:

Nope. I use this package only as legacy for old projects. Nowadays I use [django-fobi](https://pypi.python.org/pypi/django-fobi), which I wrote myself.

**Comment by stephenmcd** [comment]
Things are much more up to date now.

**Comment by barseghyanartur** [comment]
@stephenmcd:

Awesome, thanks. Another question, though.

[Latest PyPI release](https://pypi.python.org/pypi/django-forms-builder/0.13.0) is dated 2016-09-09. 
[Latest GitHub release](https://github.com/stephenmcd/django-forms-builder/releases) is dated 2012-09-06.

Any plans for better support in nearest future?

**Comment by qcaron** [comment]
Thanks! I'll do my PR and wait a bit if necessary for approval 👍
