### ISSUE TITLE
Doesn't work with Django version 2.0.3 ?

### ISSUE THREAD

**Issue by ashfaqahmed** [stephenmcd/django-forms-builder#217]
i am unable to use this library with version 2.0.3, any help or suggestion how can i do that ? really need this library, any alternative for latest Django version ?

**Comment by stephenmcd** [comment]
Current master branch supports 2.0

**Comment by ashfaqahmed** [comment]
Thank you, i will have a try

**Comment by ashfaqahmed** [comment]
I just have tried to install it manually from master-branch using "python setup.py install", it was installed successfully but when configured my app to use this it showed below depreciated errors


I just have tried to install it manually from master-branch using "python setup.py install", it was installed successfully but when configured my app to use this it showed below depreciated errors


```
File "/usr/local/lib/python3.6/site-packages/forms_builder/forms/models.py", line 5, in <module>
    from django.core.urlresolvers import reverse
ModuleNotFoundError: No module named 'django.core.urlresolvers'
```
and i am think this is [depreciated import for Django ](https://stackoverflow.com/questions/43139081/importerror-no-module-named-django-core-urlresolvers) any suggestion or comments?

**Comment by ashfaqahmed** [comment]
@stephenmcd no worries, i have resolved this and got it running for the current stable Django version.
