### ISSUE TITLE
Initial Values feed

### ISSUE THREAD

**Issue by Pijuli** [stephenmcd/django-forms-builder#224]
Hi,
I'm really stuck with this. I've been able to see my form using a template with
```
{% load forms_builder_tags %}
{% render_built_form form_instance %}
```

But I need to feed the form with some predefined data or to allow the user to fix a submitted form, that's why I need to use (I guess) the initial object to feed it in view.py. But I can't seem to find a proper example, and I'm not getting more than fails with the approach I made up, probably absolutely wrong.

Any advice/example would be higly appreciated. My head's gonna blow up.

view.py
```
from forms_builder.forms.models import Form
from forms_builder.forms.forms import FormForForm

def format_form(request):
    form_obj = Form.objects.get(slug='test')
    initial = {
        'question': 'answer',
    }
    form = FormForForm(form=form_obj, context=request, initial=initial)
    context = {
        'form': form,
    }
    return render(request, 'form.html', context)

```
form.html
```
{{ form }}
```

**Comment by stephenmcd** [comment]
What you're doing should work so I don't know what you're doing wrong. I'd suggest trying stackoverflow or the django-users mailing list.

**Comment by Pijuli** [comment]
That's how it finally ended. I missed context. Just got it 5' ago
Thank you pointing it was on the right path.

```
    form_obj = Form.objects.get(slug='test')
    initial = {
        'name': 'John',
    }
    context = Context()
    form_for_form = FormForForm(form=form_obj, context=context, initial=initial)
    context = {
        'form': form_obj,
        'form_for_form': form_for_form,
    }
    return render(request, 'form.html', context)
```
