### ISSUE TITLE
Field slug is failing with +100 chars labels

### ISSUE THREAD

**Issue by Pijuli** [stephenmcd/django-forms-builder#226]
Issue:
When creating a NEW field and putting in it a long string (+100 chars) it will fail to create, aparently because of slug. 
When creating a NEW field and putting in it a short string (-100 chars) it will create it correctly. As the slug has been correctly created then you can edit the label and set it longer than 100 chars

How to reproduce?
Create a new form, go to fields. Add a field with a long label (+100 chars), set it's type, try to save. Data error rises.
![image](https://user-images.githubusercontent.com/1220004/40230064-95dc117e-5a96-11e8-8e1c-a5ca71828b86.png)

How to avoid?
Create a new form, go to fields. Add a field with a short label (-100 chars), set it's type, save, edit, change label to long string (+100 chars), save. Done

Fix proposal:
- Cut slug when beeing created, to 100 chars
- Let the user choose slug size. Side effects?

I can do a PR if you want. Your call

**Comment by stephenmcd** [comment]
Let's just increase the length to 2000, it will need a migration too. Can you create a PR with that? Thanks

**Comment by Pijuli** [comment]
Done
https://github.com/stephenmcd/django-forms-builder/pull/227
