### ISSUE TITLE
This project needs a maintainer

### ISSUE THREAD

**Issue by bashu** [stephenmcd/django-forms-builder#255]
Hi,

This repository seems to lack maintenance, I propose myself as a new maintainer.

Could you give me the right to push in your repository or just transfer it on my account in github?

Thank you!

**Comment by bashu** [comment]
We still use it some legacy projects and I am willing to keep it maintained. If you are not sure about me, for example I maintain (or helping to maintain):

https://github.com/shanx/django-maintenancemode

https://github.com/adamcharnock/django-tz-detect

Also I adopted few Django projects and still continue maintaining them, biggest example:

https://github.com/bashu/django-easy-maps

**Comment by bashu** [comment]
cc @stephenmcd  may I bring your attention to this issue?

**Comment by DmytroLitvinov** [comment]
Hi, @stephenmcd ,
Any response would be appreciated.
